### ISSUE TITLE
Please make and tag a new release

### ISSUE THREAD

**Issue by mgorny** [kalekundert/signature_dispatch#1]
FWICS, the 0.0.0 release on pypi does not include py3.8 test fix/split. Please make a new one.

**Comment by mgorny** [comment]
Also pushing tags would be nice instead of expecting us to guess which commit corresponds to the release.

**Comment by kalekundert** [comment]
Done.  How did you find this so fast?  I only made this repository last night!

FYI, there's another project called [Dispatch](https://github.com/Lucretiel/Dispatch) that does the exact same thing as this, but also supports dispatching on argument type.  I only found it after I finished writing this.  This implementation has a slightly more succinct API, because the module is directly usable as a callable, but that's probably its only advantage over Dispatch.

**Comment by mgorny** [comment]
> Done. How did you find this so fast? I only made this repository last night!

Because I'm maintaining autoprop package in Gentoo, so I have to package its dependencies as well.

> FYI, there's another project called [Dispatch](https://github.com/Lucretiel/Dispatch) that does the exact same thing as this, but also supports dispatching on argument type. I only found it after I finished writing this. This implementation has a slightly more succinct API, because the module is directly usable as a callable, but that's probably its only advantage over Dispatch.

Are you considering switching autoprop to Dispatch? If yes, then maybe I'll wait for that to avoid packaging signature_dispatch unnecessarily.

**Comment by kalekundert** [comment]
Ah, makes sense.  I'm going to stick with `signature_dispatch`.  Sorry I made more work for you, though.  I originally wrote this function as part of autoprop, and just decided to break it out into it's own package because it seemed kinda general.  I didn't think that decision would affect anyone else. :-)

**Comment by mgorny** [comment]
No problem, as long as the package works and tests pass, it's a pleasure. I've just packaged it along with new autoprop and everything seems in order now.
